import React, { Component } from "react"
import Layout from "components/Layout/Layout"
import SEO from "utils/Seo"
import {Container} from 'reactstrap'
import {Link} from 'gatsby'

class PrivacyPage extends Component {
    render() {
        return (
            <Layout>
                <SEO title="Privacy and Cookies" />
                <Container fluid={true} className="py-4">
                    <Container>
                        <h1>Privacy Policy</h1>
                        <p><strong>Introduction</strong></p>
                        <p>This website, controlled by Dewynters Limited. Dewynters Limited is the Data Controller, for the purposes of Data Protection Law, when your personal information is processed as a result of your visit to this website.</p>
                        <p>We are committed to providing you with relevant information about, and control over, how we process your personal information.</p>
                        <p>This policy explains what personal information we may record, why we do so, how you may control the use of your information and how we protect your information. Details of your legal rights and how to exercise them are also set out below.</p>
                        <p>This policy was last updated on 26/03/2019. Any future changes to our policy will be reflected <a href="#cookie-policy">HERE</a>.</p>

                        <p><strong>Contacting us</strong></p>
                        <p>Questions, comments and requests regarding this privacy policy are welcomed and should be addressed by email to <a href="mailto:info@dewynters.com">info@dewynters.com</a></p>

                        <strong>What Does This Policy Cover?</strong>
                        <p>We process your personal information gathered on this website in order to tailor our marketing to your needs and to improve our website for future customers.  The specific purposes for which we may process information, and the lawful basis on which we do so in each case, are set out below.</p>

                        <p><strong>Tailoring this website to your needs</strong></p>
                        <p>We want to make our website easy to personalise.  We use preference cookies to store your preferences, such as website language selection, so that you do not need to make the same selections every time you visit our website.  These cookies, stored by your browser on your device, will retain your preference choices [for 30 days, until you delete them].  We record your consent to store cookies when you first visit the site and click on the cookie notice, and we provide details of how to change your settings <a href="#cookie-policy">HERE</a></p>

                        <p><strong>Improving the effectiveness of our website</strong></p>
                        <p>We want to make sure that our website enables people to learn about the show and to book tickets and that the site meets the needs of our customers and is easy to use. To do this, we need to understand how people use this site, where they spend time and which pages they find less useful.  We use Google Analytics platform to understand how you and other visitors use our website, for example recording in what order pages are visited and how long is spent on each, so that we may improve the website in future. [Google Analytics platform’s privacy policy may be found <a href="https://policies.google.com/privacy?hl=en" target="_blank" rel="noreferrer noopener">here</a>].  We record your consent to store site analytics cookies when you first visit the site and click on the cookie notice. The lawful basis on which we process these analytics cookies is our legitimate interest in improving our website as we believe that the use of such cookies is not intrusive.</p>

                        <p><strong>Targeting and measuring the effectiveness of our digital advertising</strong></p>
                        <p>We know that many people visit a show site several times to learn about the show and dates when tickets are available before deciding to book tickets.  We want to make sure that our digital advertisements on other websites and social media are seen by people likely to be interested in the show, including by visitors to this site who have not yet booked. We also want to understand the effectiveness of our advertising in encouraging visits to the website and ticket bookings so that we may improve it in future for example by reviewing the choice of advertising design and the websites and advertising networks used to reach possible customers. Achieving this may involve showing different versions of advertisements to different customers to measure the responses generated by each. We may use available browsing history, including visits to this website, to identify people to whom we wish to show advertisements on websites operated by third parties and to record how many visitors are referred to our site from other sites.  We use Sizmek advertising tracking cookies to achieve this and process these cookies on the basis of legitimate interest. We believe that showing relevant advertisements is in your interest as well as ours and we do not believe that such personalisation is generally considered intrusive.] We respect any decision not to participate in personalised advertising, in which case third party sites may show you non-personalised advertising and you may still see advertisements for our show. We record your consent to store advertising tracking cookies when you first visit the site and click on the cookie notice. We use Sizmek to track our advertising. Details of how long your data is stored and how transfers outside the EEA are protected may be found in their <a href="https://www.sizmek.com/privacy-policy/" target="_blank" rel="noreferrer noopener">Privacy Policy</a>.  Our tracking cookie information is not shared with third parties for their own use, though we may use it to reconcile advertising costs with the publishers of third party sites. </p>

                        <p><strong>Data Transfers</strong></p>
                        <p>The personal information collected while you use this website may be transferred to countries outside the European Economic Area (EEA). This may happen, for example, when the computer servers used to host the website or our advertising and marketing systems are located in a country outside the EEA. If we transfers your personal information outside of the EEA in this way, we will take steps to ensure that your privacy rights continue to be appropriately protected.</p>


                        <p><strong>Your rights</strong></p>
                        <p>We want to be transparent about how we process your data and to ensure that you can exercise your legal rights:</p>
                        <ul>
                            <li>To be informed – via this Privacy Policy which sets out how we collect and process data</li>
                            <li>To access your data – please contact <a href="mailto:info@dewynters.com">info@dewynters.com</a> if you wish to confirm what data we hold about you</li>
                            <li>To have your data corrected - please contact <a href="mailto:info@dewynters.com">info@dewynters.com</a> if you feel that data held is incorrect and want this rectified</li>
                            <li>To have processing of your data ceased - please contact <a href="mailto:info@dewynters.com">info@dewynters.com</a> if you wish us to cease processing your data without erasing it</li>
                            <li>To have your data erased – please contact <a href="mailto:info@dewynters.com">info@dewynters.com</a> to request deletion of data that we hold about you</li>
                            <li>To data portability – we process data only to personalise our services to you so do not consider it appropriate to pass your data to other organisations. Some banks and utilities offer facilities to switch accounts, but this is not applicable to our business.</li>
                            <li>To object to processing of your data on the basis of legitimate interest or for statistical purposes – please contact <a href="mailto:info@dewynters.com">info@dewynters.com</a>, or amend your cookie settings.</li>
                        </ul>
                        <p><strong>Complaints</strong></p>
                        <p>To exercise all relevant rights, queries of complaints please in the first instance contact <a href="mailto:info@dewynters.com">info@dewynters.com</a></p>
                        <p>You can contact the Information Commissioners Office on 0303 123 1113 or via email <a href="https://ico.org.uk/global/contact-us/email/">https://ico.org.uk/global/contact-us/email/</a> or at the Information Commissioner's Office, Wycliffe House, Water Lane, Wilmslow, Cheshire. SK9 5AF.</p>

                        <Link to="/">Back to home</Link>
                    </Container>
                </Container>
                <Container fluid={true} className="py-4">
                    <Container>
                        <h1 id="cookie-policy">Cookie Policy</h1>
                        <p><strong>Cookies and how they benefit you:</strong></p>
                        <p>Our website uses cookies, as almost all websites do, to help provide you with the best experience we can.
                            Cookies are small text files that are placed on your computer or mobile phone when you browse
                            websites.</p>

                        <p><strong>Dewynters Limited uses cookies for three main purposes:</strong></p>
                        <ul>
                            <li>To ensure the website works, in particular for online booking</li>
                            <li>To monitor website performance and help us make improvements in the future</li>
                            <li>To tailor our marketing, and use tools such as Google AdWords to communicate more effectively
                                through web advertising.
                            </li>
                        </ul>
                        <p><strong>Our cookies help us:</strong></p>
                        <ul>
                            <li>Make our website work as you’d expect</li>
                            <li>Save you having to login every time you visit the site</li>
                            <li>Remember your settings during and between visits</li>
                            <li>Improve the speed/security of the site</li>
                            <li>Allow you to share pages with social networks like Facebook</li>
                            <li>Continuously improve our website for you</li>
                            <li>Make our marketing more efficient (ultimately helping us to offer the service we do at the price we
                                do)
                            </li>
                        </ul>
                        <p><strong>We do not use cookies to:</strong></p>
                        <ul>
                            <li>Collect any sensitive information</li>
                            <li>Pass personally identifiable data to third parties</li>
                            <li>Pay sales commissions</li>
                        </ul>
                        <p>You can learn more about all the cookies we use below:</p>

                        <p><strong>Google Analytics</strong></p>
                        <p>This monitors how people use our site – for example the browser they use and the pages they visit. It’s
                            used to assess our website’s performance and to help us plan improvements.</p>

                        <p><strong>Facebook / Instagram / Twitter / Snapchat</strong></p>
                        <p>This communicates with Facebook / Instagram / Snapchat / Twitter activity on our website. In a similar
                            way to DoubleClick / Sizmek it allows us to reduce our costs (and keep our prices low) by using digital
                            adverts to encourage you to visit us. Don’t worry - we are unable to proactively reach out to you as the
                            whole process is entirely anonymised.
                        </p>
                        <p><strong>Session</strong></p>
                        <p>This cookie is a transient cookie (it is erased when you close the browser). It acts as a small amount
                            of memory to remember what you’ve done on past pages.
                        </p>

                        <p><strong>Granting us permission to use cookies</strong></p>
                        <p>If the settings on your software that you are using to view this website (your browser) are adjusted to
                            accept cookies we take this, and your continued use of our website, to mean that you are fine with this.
                            Should you wish to remove or not use cookies from our site you can learn how to do this below; however,
                            doing so will likely mean that our site will not work as you would expect.</p>
                        <p><strong>Our own cookies</strong></p>
                        <p>We use cookies to make our website work including:</p>
                        <ul>
                            <li>Remembering your search settings</li>
                        </ul>
                        <p><strong>Third party functions</strong></p>
                        <p>Our site, like most websites, includes functionality provided by third parties. A common example is an
                            embedded YouTube video. Disabling these cookies will likely break the functions offered by these third
                            parties.</p>
                        <p><strong>Social website cookies</strong></p>
                        <p>So you can easily “like” or share our content on the likes of Facebook and Twitter we have included
                            sharing buttons on our site.</p>
                        <p>The privacy implications of this will vary depending on the social network and will be dependent on the
                            privacy settings you have chosen on these networks.</p>
                        <p><strong>Anonymous visitor statistics cookies</strong></p>
                        <p>We use cookies to compile visitor statistics such as how many people have visited our website, what type
                            of technology they are using (e.g. Mac or Windows, which helps to identify when our site isn’t working
                            as it should for particular technologies), how long they spend on the site, what page they look at etc.
                            This helps us to continuously improve our website. These so called “analytics” programs also tell us if,
                            on an anonymous basis, how people reached this site (e.g. from a search engine) and whether they have
                            been here before; this helps us to put more money into developing our services for you instead of
                            marketing spend.</p>
                        <p><strong>We use advertising cookies</strong></p>
                        <p>Cookies are widely used in online advertising. Neither us, advertisers or our advertising partners can
                            gain personally identifiable information from these cookies. We only work with advertising partners who
                            work to accepted privacy standards such as <a href="http://www.youronlinechoices.com/goodpractice" target="_blank"
                                                                          rel="noreferrer noopener">http://www.youronlinechoices.com/goodpractice</a></p>
                        <p>You can learn more about online advertising at http://www.youronlinechoices.com . You can opt-out of
                            almost all advertising cookies at http://www.youronlinechoices.com/uk/your-ad-choices although we would
                            prefer that you didn’t, as ultimately advertising helps keep much of the internet free. It is also worth
                            noting that opting out of advertising cookies will not mean you won’t see adverts, just simply that they
                            won’t be tailored to you any longer.</p>
                        <p><strong>We use:</strong></p>
                        <ul>
                            <li>DoubleClick – privacy policy owned by Google; Sizmek – privacy policy owned by Sizmek</li>
                            <li>Remarketing cookies</li>
                        </ul>
                        <p>You may notice that sometimes after visiting a site you see increased numbers of adverts from the site
                            you visited. This is because advertisers, including ourselves, pay for these adverts. The technology to
                            do this is made possible by cookies and as such we may place a so called “remarketing cookie” during
                            your visit. We use these adverts to offer special offers etc to encourage you to come back to our site.
                            Don’t worry - we are unable to proactively reach out to you as the whole process is entirely
                            anonymised. You can opt out of these cookies at any time as explained above.</p>
                        <p><strong>Managing cookies</strong></p>
                        <p>Cookies cannot be used by themselves to identify you. You can easily control and disable cookies through
                            your browser settings.</p>
                        <p>All browsers are different – for more information on cookies in general, visit the following external
                            links:</p>
                        <p><a className="color-red" href="http://www.aboutcookies.org/"
                            target="_blank" rel="noreferrer noopener">www.aboutcookies.org</a><br/>
                            <a className="color-red" href="http://www.youronlinechoices.eu/"
                                target="_blank" rel="noreferrer noopener">www.youronlinechoices.eu</a></p>
                        <p>Depending on the browser you are using, cookies can be managed according to the steps shown in the below
                            table.</p>
                        <p>Please be aware that by limiting or deleting cookies, your experience of our website might not be the
                            best it could be. If you have any questions about cookies, please contact the Data Protection
                            Manager admin@openairtheatre.com</p>
                        <p><strong>Turning cookies off</strong></p>
                        <p>You can usually switch cookies off by adjusting your browser settings to stop it from accepting cookies.
                            Doing so, however, will likely limit the functionality of this site - and a large proportion of
                            the world’s websites - as cookies are a standard part of most modern websites.</p>
                        <p>Most web browsers allow some control of most cookies through the browser settings. To find out more about
                            cookies, including how to see what cookies have been set and how to manage and delete them, visit <a href="https://www.aboutcookies.org/" target="_blank"
                                                                                                                                 rel="noreferrer noopener">www.aboutcookies.org</a> or <a href="http://www.allaboutcookies.org/"
                                                                                                                                                                                          target="_blank"
                                                                                                                                                                                          rel="noreferrer noopener">www.allaboutcookies.org</a>.</p>
                        <p>To opt out of being tracked by Google Analytics across all websites visit <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noreferrer noopener">http://tools.google.com/dlpage/gaoptout</a>.</p>
                        <p>It may be that your concerns around cookies relate to so called “spyware”. Rather than switching off
                            cookies in your browser you may find that anti-spyware software achieves the same objective by
                            automatically deleting cookies considered to be invasive. Learn more about managing cookies with
                            anti-spyware software.</p>

                        <Link to="/">Back to home</Link>
                    </Container>
                </Container>
            </Layout>
        )
    }

}

export default PrivacyPage